# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2017-06-10 05:53
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0005_course_teacher'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='learn',
            field=models.CharField(default=b'', max_length=300, verbose_name='\u5b66\u5230\u4ec0\u4e48'),
        ),
        migrations.AddField(
            model_name='course',
            name='notice',
            field=models.CharField(default=b'', max_length=400, verbose_name='\u8bfe\u7a0b\u987b\u77e5'),
        ),
    ]
