# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2017-06-18 04:54
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0008_video_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='video',
            name='poster',
            field=models.ImageField(blank=True, max_length=200, null=True, upload_to=b'course/poster/%Y/%m', verbose_name='\u5c01\u9762'),
        ),
    ]
