# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2017-07-18 03:45
from __future__ import unicode_literals

import DjangoUeditor.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0011_auto_20170718_1058'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='detail',
            field=DjangoUeditor.models.UEditorField(blank=True, default=b'', verbose_name='\u8bfe\u7a0b\u8be6\u60c5'),
        ),
    ]
