# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2017-07-18 04:39
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0012_auto_20170718_1145'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='detail',
            field=models.TextField(verbose_name='\u8bfe\u7a0b\u8be6\u60c5'),
        ),
    ]
